// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-GTUmUxVl7oq-UImj3KkNlMOIGd85ss8',
    appId: '1:1009340811894:web:ee6e17de7e8933ba2eed57',
    messagingSenderId: '1009340811894',
    projectId: 'councellingapp-10dca',
    authDomain: 'councellingapp-10dca.firebaseapp.com',
    storageBucket: 'councellingapp-10dca.appspot.com',
    measurementId: 'G-9ZS33ENG2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqNLtO_0x31Q1WInpXm7jODjF3e-3SXlU',
    appId: '1:1009340811894:android:63a0aaf32acdc4652eed57',
    messagingSenderId: '1009340811894',
    projectId: 'councellingapp-10dca',
    storageBucket: 'councellingapp-10dca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaBcTjOU3CrU3W0OXSx-7_q_oLNU6W3XE',
    appId: '1:1009340811894:ios:ec14049ef3abfd122eed57',
    messagingSenderId: '1009340811894',
    projectId: 'councellingapp-10dca',
    storageBucket: 'councellingapp-10dca.appspot.com',
    iosClientId: '1009340811894-jh2ld6fo8jrpeb3pcekdjv4n22tdaa67.apps.googleusercontent.com',
    iosBundleId: 'com.example.intelligentEducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaBcTjOU3CrU3W0OXSx-7_q_oLNU6W3XE',
    appId: '1:1009340811894:ios:ec14049ef3abfd122eed57',
    messagingSenderId: '1009340811894',
    projectId: 'councellingapp-10dca',
    storageBucket: 'councellingapp-10dca.appspot.com',
    iosClientId: '1009340811894-jh2ld6fo8jrpeb3pcekdjv4n22tdaa67.apps.googleusercontent.com',
    iosBundleId: 'com.example.intelligentEducation',
  );
}
